#!/bin/bash
#===============================================================
#
# [ author: Krzysztof Baranski ]
#
#       CLIENT ( setup )
#
#===============================================================

setuplock='.setuplock'

echo "
---------------------------------------------------
-                  SETUP CLIENT                   -
---------------------------------------------------"
#--------------------------------------------------------------| check if configured
if [ -f $setuplock ]
then
	echo "Project alredy configured"
	exit 1
fi

touch $setuplock
chmod 0 $setuplock

echo "---------------------------------------------------
"
