#!/bin/bash
#===============================================================
#
# [ author: Krzysztof Baranski ]
#
#       CARRIER ( setup )
#
#===============================================================

db='.db'
setuplock='.setuplock'

echo "
---------------------------------------------------
-                  SETUP CARRIER                  -
---------------------------------------------------"
#--------------------------------------------------------------| check if configured
if [ -f $setuplock ]
then
	echo "Project alredy configured"
	exit 1
fi

#--------------------------------------------------------------| check SQLite
echo "Checking SQLite3..."
which sqlite3
if [ $? -eq 0 ]
then
	echo "OK!"
else
	echo "SQLite3 not found. Please install SQLite3"
	exit 1
fi

#--------------------------------------------------------------| prepare database
echo "Preparing database..."
echo -n "Database name: "
read dbname

sqlite3 database/$dbname < database/create.sql
if [ "$?" == "0" ]
then
	echo "OK!"
else
	echo "Database creation failed!"
	exit 1
fi

echo "$dbname" > $db
chmod -w $db

touch $setuplock
chmod 0 $setuplock

echo "---------------------------------------------------
"