#!/bin/bash
#===============================================================
#
# [ author: Krzysztof Baranski ]
#
#       CARRIER ( setup )
#
#===============================================================

setuplock='.setuplock'

echo "
---------------------------------------------------
-                  SETUP CARRIER                  -
---------------------------------------------------"
#--------------------------------------------------------------| check if configured
if [ -f $setuplock ]
then
	echo "Project alredy configured"
	exit 1
fi

#--------------------------------------------------------------| check SQLite
echo "Checking SQLite3..."
which sqlite3
if [ $? -eq 0 ]
then
	echo "OK!"
else
	echo "SQLite3 not found. Please install SQLite3"
	exit 1
fi

#--------------------------------------------------------------| set carrier name
echo
echo -n "Carrier name: "
read carrier_name
sed -i config.properties -e '/carrier_name/ccarrier_name='"$carrier_name"

#--------------------------------------------------------------| set server port
echo -n "Set server port: "
read server_port
sed -i config.properties -e '/server_port/cserver_port='"$server_port"

#--------------------------------------------------------------| set database name
echo -n "Database name: "
read dbname
sed -i config.properties -e '/database_name/cdatabase_name='"$dbname"

#--------------------------------------------------------------| prepare database
echo "Preparing database..."
sqlite3 database/$dbname < database/create.sql
if [ "$?" == "0" ]
then
	echo "OK!"
else
	echo "Database creation failed!"
	exit 1
fi

#--------------------------------------------------------------| setuplock
touch $setuplock
chmod 0 $setuplock

echo "---------------------------------------------------
"