#!/bin/bash
#===============================================================
#
# [ author: Krzysztof Baranski ]
#
#       CARRIER ( uninstall )
#
#===============================================================

db='.db'
setuplock='.setuplock'
project_name='carrier'
build='.build'
source='source'
main_class='Application'
commons_dir='../commons'
commons_jar='commons.jar'
project_jar=$project_name.jar

echo "
---------------------------------------------------
-                UNINSTALL CARRIER                -
---------------------------------------------------"

#--------------------------------------------------------------| remove setup lock
echo "Removing setup lock..."
rm -f $setuplock
if [ $? -eq 0 ]
then
	echo "OK!"
else
	echo "Error!"
fi

#--------------------------------------------------------------| remove database
if [ -f $db ]
then
	echo "Removing database..."
	dbname=$( cat $db )
	rm -f database/$dbname
	if [ $? -eq 0 ]
	then
		echo "OK!"
	else
		echo "Error!"
	fi
fi

#--------------------------------------------------------------| remove database name
if [ -f $db ]
then
	echo "Removing database name..."
	rm -f $db
	if [ $? -eq 0 ]
	then
		echo "OK!"
	else
		echo "Error!"
	fi
fi


#--------------------------------------------------------------| remove jars
echo "Removing jars..."
rm -vf libs/$commons_jar
rm -vf $project_jar

#--------------------------------------------------------------| remove logs
if [ -d logs ]
then
	echo "Removing logs..."
	rm -rvf logs
fi

echo "---------------------------------------------------
"
