#!/bin/bash
#===============================================================
#
# [ author: Krzysztof Baranski ]
#
#       SERVER ( setup )
#
#===============================================================

setuplock='.setuplock'

echo "
---------------------------------------------------
-                  SETUP SERVER                   -
---------------------------------------------------"
#--------------------------------------------------------------| check if configured
if [ -f $setuplock ]
then
	echo "Project alredy configured"
	exit 1
fi

#--------------------------------------------------------------| set server port
echo -n "Set server port: "
read server_port
sed -i config.properties -e '/server_port/cserver_port='"$server_port"

#--------------------------------------------------------------| setuplock
touch $setuplock
chmod 0 $setuplock

echo "---------------------------------------------------
"
